### ISSUE TITLE
No metadata.yaml file generated

### ISSUE THREAD

**Issue by Fixit-Davide** [berndpfrommer/rosbag2_composable_recorder#1]
Hi, 
I am currently trying to implement the rosbag2 functionality inside one of mine component manager (with intra-process enabled) to save huge pointcloud data. 
I was able to use your packet and it is working very well but I am facing a bug, while the filte .db3 is correctly generated no metadata file (.yaml) is created when i kill the process. 
I have managed to find a workaround to this problem by using the command "ros2 bag reindex" but still, I am curios if you were facing the same problem. 
Currently working using ROS 2 Humble on Ubuntu 20.04.

**Comment by berndpfrommer** [comment]
Hmm, I have never seen that, but then I have only tested it on Galactic/Ubuntu 20.04.
I think Humble switched away from sqlite to a different file format. Care to try and see if that helps?
Question: how do you run Humble on Ubuntu 20.04? I went through the pain of upgrading to Ubuntu 22.04 to accomplish that...

**Comment by roncapat** [comment]
Hi, we discovered the stop() function [was added in rolling (and thus iron) only three weeks ago](https://github.com/ros2/rosbag2/commit/a218e379211b5a571817dcc437044bffcf60e66d) and not backported in humble... 

For humble on 20.04: we are on a source build, and you have to fight a bit with python versions and QT stuff, mainly. Thanks to Nvidia Jetpack not being aligned on the last Ubuntu LTS! 🥲

**Comment by berndpfrommer** [comment]
Just tested on Humble / Ubuntu 22.04 and the meta yaml file is there. Strange that it's not working for you.
Could it be something with the launch file? Here is what I'm using for launching:
https://github.com/berndpfrommer/metavision_ros_driver/blob/master/launch/recording_driver.launch.py

I also pushed a tiny fix, but that should not make a difference.

**Comment by berndpfrommer** [comment]
I have a xavier on Ubuntu 20.04 as well so I'm running galactic there but that is already getting long in the tooth.

**Comment by Fixit-Davide** [comment]
I've managed to make it work by back-porting the method stop() to humble and creating a service to stop the recording without killing the node. Thanks for your availability!!

**Comment by l4es** [comment]
Hi @Fixit-Davide, @roncapat ,

I followed  your [patch](https://github.com/Fixit-Davide/rosbag2_composable_recorder/commit/5607a1d95f27d8db80feff562b0fdc6074f82a5a) for adding the **stop_recording** service. However, triggering the **stop_recording** service also killed the application that includes the recorder in the launch file and by consequence, the metadata.yaml is empty. 

Should I also re-build the rosbag2 from source for humble on the Nvidia Jetson Orin NX since I followed the instruction for installing the ROS2 Humble here : https://qiita.com/ntrlmt/items/50b49fb43b4439ac165b

Thanks and best regards,
Khang

**Comment by roncapat** [comment]
Hi @l4es, on an Orin platform my suggestion is to go with a full Jazzy build from source, it will include support for rosbag2 composition out-of-the-box. Since I already use Iron/Jazzy on my Jetson Orin, I unfortunately won't be able to reproduce your issue on Humble and help you solve the error you see.

**Comment by l4es** [comment]
Hi @roncapat,

Thanks for your comment. In the meantime, I was able to clone and recompile the rosbag2 from source (branch humble) and re-test the start_recording/stop_recording services, it works like a charm without killing the app or the recorder node.

Best Regards,
Khang
